# Generated by Django 6.0.4 on 2026-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
