# Generated by Django 6.0.4 on 2026-05-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_department'),
        ('students', '0002_alter_studentrecord_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department'),
        ),
        migrations.AddField(
            model_name='studentupload',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department'),
        ),
    ]
