# Generated by Django 6.0.4 on 2026-05-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election', 'name')},
        ),
    ]
