# Generated by Django 6.0.4 on 2026-05-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_candidate_department'),
        ('institutions', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.branch'),
        ),
    ]
