# Generated by Django 6.0.4 on 2026-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
