# Generated by Django 6.0.4 on 2026-05-08 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_candidate_image'),
        ('institutions', '0004_department'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['department'], name='voting_vote_departm_fae64b_idx'),
        ),
    ]
