# Generated by Django 6.0.4 on 2026-05-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
